import {
   Img1,
   Img10,
   Img11,
   Img12,
   Img2,
   Img3,
   Img4,
   Img5,
   Img6,
   Img7,
   Img8,
   Img9,
} from '../../assets/images'

export const BoardColors = [
   {
      id: '1',
      title: 'Boardname',
      isFavourite: false,
      background: Img1,
   },
   {
      id: '2',
      title: 'Boardname',
      isFavourite: false,
      background: Img2,
   },
   {
      id: '3',
      title: 'Boardname',
      isFavourite: false,
      background: Img3,
   },
   {
      id: '4',
      title: 'Boardname',
      isFavourite: false,
      background: Img4,
   },
   {
      id: '5',
      title: 'Boardname',
      isFavourite: false,
      background: Img5,
   },
   {
      id: '6',
      title: 'Boardname',
      isFavourite: false,
      background: Img6,
   },
   {
      id: '7',
      title: 'Boardname',
      isFavourite: false,
      background: Img7,
   },
   {
      id: '8',
      title: 'Boardname',
      isFavourite: false,
      background: Img8,
   },
   {
      id: '9',
      title: 'Boardname',
      isFavourite: false,
      background: Img9,
   },
   {
      id: '10',
      title: 'Boardname',
      isFavourite: false,
      background: Img10,
   },
   {
      id: '11',
      title: 'Boardname',
      isFavourite: false,
      background: Img11,
   },
   {
      id: '18',
      title: 'Boardname',
      isFavourite: false,
      background: Img12,
   },
   {
      id: '12',
      title: 'Boardname',
      isFavourite: false,
      background: '#CBCBCB',
   },
   {
      id: '13',
      title: 'Boardname',
      isFavourite: false,
      background: '#B04632',
   },
   {
      id: '14',
      title: 'Boardname',
      isFavourite: false,
      background: '#519839',
   },
   {
      id: '15',
      title: 'Boardname',
      isFavourite: false,
      background: '#D29034',
   },
   {
      id: '16',
      title: 'Boardname',
      isFavourite: false,
      background: '#89609E',
   },
   {
      id: '17',
      title: 'Boardname',
      isFavourite: false,
      background: '#005C92',
   },
]
