export const favourites = [
   {
      id: 1,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbhYG8hBraKFu-tgvh337LKvqGmW3K8eftbA&usqp=CAU',
      title: 'Title',
      text: 'Board',
      favourite: 'true',
   },
   {
      id: 2,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbhYG8hBraKFu-tgvh337LKvqGmW3K8eftbA&usqp=CAU',
      title: 'Title',
      text: 'Board',
      favourite: 'true',
   },
   {
      id: 3,
      title: 'Taigan',
      text: 'Workspaces',
      favourite: 'true',
   },
   {
      id: 4,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbhYG8hBraKFu-tgvh337LKvqGmW3K8eftbA&usqp=CAU',
      title: 'Title',
      text: 'Board',
      favourite: 'true',
   },
   {
      id: 5,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbhYG8hBraKFu-tgvh337LKvqGmW3K8eftbA&usqp=CAU',
      title: 'Title',
      text: 'Board',
      favourite: 'true',
   },
   {
      id: 6,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbhYG8hBraKFu-tgvh337LKvqGmW3K8eftbA&usqp=CAU',
      title: 'Title',
      text: 'Board',
      favourite: 'true',
   },
   {
      id: 7,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbhYG8hBraKFu-tgvh337LKvqGmW3K8eftbA&usqp=CAU',
      title: 'Title',
      text: 'Board',
      favourite: 'true',
   },
]
