export const notificationsPanel = [
   {
      id: 1,
      titleofBoard: 'Title of the board',
      nameofColumn: 'Name of the column',
      img: 'https://i.pinimg.com/564x/9f/60/86/9f60862fd05106a1ba2156ae7b0d3445.jpg',
      nameOfPerson: 'Arzuu',
      notification: 'Moved to list Done',
      addedDate: 'Sep 15 at 13:23 PM',
   },
   {
      id: 2,
      titleofBoard: 'Title of the board',
      nameofColumn: 'Name of the column',
      img: 'https://i.pinimg.com/564x/5e/a3/80/5ea3807115390a30dfffadf6ec28750c.jpg',
      nameOfPerson: 'Aidin',
      notification: 'Was due 10 min ago',
      addedDate: 'Sep 15 at 13:23 PM',
   },
   {
      id: 3,
      titleofBoard: 'Title of the board',
      nameofColumn: 'Name of the column',
      img: 'https://i.pinimg.com/564x/ea/83/68/ea8368eea947c816f80bc97bbb7afcf0.jpg',
      nameOfPerson: 'Emir',
      notification:
         'Lorem ipsum dolor sit amet consectetur, adipisicing elit.Possimus suscipit distinctio quasi, reprehenderit aliquam,beatae fuga eius sunt porro harum, incidunt earum in. At veritatis optio aperiam. Cumque, corrupti et.',
      addedDate: 'Sep 15 at 13:23 PM',
   },
   {
      id: 4,
      titleofBoard: 'Title of the board',
      nameofColumn: 'Name of the column',
      img: 'https://i.pinimg.com/564x/56/eb/a1/56eba18aeed81351df6a280a0239ec81.jpg',
      nameOfPerson: 'Beku',
      notification: 'Moved to list Done',
      addedDate: 'Sep 15 at 13:23 PM',
   },
   {
      id: 5,
      titleofBoard: 'Title of the board',
      nameofColumn: 'Name of the column',
      img: 'https://i.pinimg.com/564x/69/02/cd/6902cd3556639678ffb92bb58770d7ba.jpg',
      nameOfPerson: 'Ali',
      notification: 'Moved to list Done',
      addedDate: 'Sep 15 at 13:23 PM',
   },
   {
      id: 6,
      titleofBoard: 'Title of the board',
      nameofColumn: 'Name of the column',
      img: 'https://i.pinimg.com/564x/78/1e/d8/781ed87c7a009efdc27dea7726342326.jpg',
      nameOfPerson: 'Amina',
      notification:
         'Lorem ipsum dolor sit amet consectetur, adipisicing elit.Possimus suscipit distinctio quasi, reprehenderit aliquam,beatae fuga eius sunt porro harum, incidunt earum in. At veritatis optio aperiam. Cumque, corrupti et.',
      addedDate: 'Sep 15 at 13:23 PM',
   },
   {
      id: 7,
      titleofBoard: 'Title of the board',
      nameofColumn: 'Name of the column',
      img: 'https://i.pinimg.com/564x/69/02/cd/6902cd3556639678ffb92bb58770d7ba.jpg',
      nameOfPerson: 'Ali',
      notification: 'Moved to list Done',
      addedDate: 'Sep 15 at 13:23 PM',
   },
]
